# Generated by Django 5.0.1 on 2024-04-07 16:14

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='News/Transportation/', verbose_name='تصویر')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'db_table': 'news_transportation',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
