# Generated by Django 4.2.7 on 2023-11-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codemeli',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='کد ملی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'مرد'), ('1', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='موبایل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_marriage',
            field=models.CharField(blank=True, choices=[('', 'انتخاب کنید'), ('0', 'متاهل'), ('1', 'مجرد')], max_length=2, verbose_name='وضعیت تاهل'),
        ),
    ]
