# Generated by Django 5.0.1 on 2024-04-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_age_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='codemeli',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
