# Generated by Django 4.2.7 on 2023-11-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'مشاوره', 'verbose_name_plural': 'مشاوره'},
        ),
    ]
