# Generated by Django 4.2.7 on 2023-11-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True, 'verbose_name': 'تخصص', 'verbose_name_plural': 'تخصص'},
        ),
    ]
