# Generated by Django 5.0.1 on 2024-03-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Member/Transportation_Air/', verbose_name='تصویر')),
            ],
        ),
    ]
