# Generated by Django 5.0.1 on 2024-03-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation_air',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Air/', verbose_name='تصویر'),
        ),
    ]
