# Generated by Django 5.0.1 on 2024-03-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_alter_transportation_air_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_Maritime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Air/', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation_Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Air/', verbose_name='تصویر')),
            ],
        ),
    ]
