# Generated by Django 5.0.1 on 2024-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_transportation_maritime_transportation_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
            ],
        ),
    ]
