# Generated by Django 5.0.1 on 2024-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_transportation_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(blank=True, verbose_name='نام و نام خانوادگی')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Air/', verbose_name='تصویر')),
            ],
        ),
    ]
