# Generated by Django 5.0.1 on 2024-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_transportation_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation_maritime',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Maritime/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='transportation_members',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Members/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='transportation_road',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Road/', verbose_name='تصویر'),
        ),
    ]
