# Generated by Django 5.0.1 on 2024-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_transportation_members_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='نام و نام خانوادگی')),
                ('status', models.BooleanField(verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Transportation_Certificate/', verbose_name='تصویر')),
            ],
        ),
    ]
