# Generated by Django 5.0.1 on 2024-04-07 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_transportation_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation_air',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
